(function(){
const cfg=window.REVIEW_CONFIG||{}; const ready=Boolean(window.supabase && cfg.supabaseUrl && cfg.supabaseAnonKey && !String(cfg.supabaseUrl).includes('YOUR-PROJECT') && !String(cfg.supabaseAnonKey).includes('YOUR_PUBLIC'));
const gate=document.getElementById('gate'),dash=document.getElementById('dash'), list=document.getElementById('inboxList'), gateStatus=document.getElementById('gateStatus'), dashStatus=document.getElementById('dashStatus');
const labels={overall:'Overall impression',about:'About Me',projects:'Projects',experience:'Experience & Activities',credentials:'Credentials & learning',visual:'Visual Diary','my-take':'My Take',journal:'Journal',future:'Vision & next steps'}; let rows=[]; let currentFilter='all';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));} function fmt(v){try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));}catch{return String(v||'');}}
if(!ready){gateStatus.textContent='Review access is not configured yet. Add your Supabase values to review-config.js.';return;}
const client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
function render(){const filtered=currentFilter==='all'?rows:rows.filter(r=>(r.status||'new')===currentFilter); if(!filtered.length){list.innerHTML='<div class="empty">No notes in this view.</div>';return;} list.innerHTML=filtered.map(r=>`<article class="note"><div class="note-meta"><span>${esc(labels[r.section_key]||r.section_key)} · ${esc(r.feedback_type||'Thought')}</span><span>${esc(fmt(r.created_at))}</span></div><h3>${esc(r.author_name||'Mentor')}</h3><p>${esc(r.content)}</p><span class="pill">${esc(r.status||'new')}</span>${r.reply?`<div class="reply-box"><div class="k">MARIE'S REPLY</div><p style="margin-top:7px">${esc(r.reply)}</p></div>`:`<div class="reply-box"><div class="k">REPLY TO THIS NOTE</div><textarea data-reply="${esc(r.id)}" placeholder="Write a short response…"></textarea><div class="reply-row"><button class="btn btn-dark reply-btn" data-id="${esc(r.id)}">Save reply</button><button class="filter mark-btn" data-id="${esc(r.id)}" data-status="addressed">Mark as addressed</button></div></div>`}</article>`).join('');
}
async function load(){const {data:{session}}=await client.auth.getSession(); if(!session || !cfg.ownerEmail || session.user.email?.toLowerCase()!==cfg.ownerEmail.toLowerCase()){dash.classList.add('hidden');gate.classList.remove('hidden');return;} gate.classList.add('hidden');dash.classList.remove('hidden');document.getElementById('me').textContent=session.user.email; const {data,error}=await client.from('mentor_comments').select('*').order('created_at',{ascending:false}); if(error){dashStatus.textContent=error.message;return;} rows=data||[]; document.getElementById('newCount').textContent=rows.filter(r=>(r.status||'new')==='new').length; document.getElementById('openCount').textContent=rows.filter(r=>['new','in progress'].includes(r.status||'new')).length; document.getElementById('doneCount').textContent=rows.filter(r=>(r.status||'new')==='addressed').length; render();}

document.getElementById('login')?.addEventListener('click',async()=>{const email=document.getElementById('email').value.trim(); if(!email){gateStatus.textContent='Enter your email address.';return;} gateStatus.textContent='Sending your secure link…'; const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}}); gateStatus.textContent=error?error.message:'Check your inbox for your secure sign-in link.';});
document.getElementById('logout')?.addEventListener('click',async()=>{await client.auth.signOut();await load();});
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');currentFilter=btn.dataset.filter;render();}));
list?.addEventListener('click',async e=>{const replyBtn=e.target.closest('.reply-btn');const markBtn=e.target.closest('.mark-btn'); if(replyBtn){const id=replyBtn.dataset.id;const area=list.querySelector(`textarea[data-reply="${CSS.escape(id)}"]`);const reply=(area?.value||'').trim();if(!reply)return;const {error}=await client.from('mentor_comments').update({reply,replied_at:new Date().toISOString(),status:'in progress'}).eq('id',id);if(error){dashStatus.textContent=error.message;return;}dashStatus.textContent='Reply saved.';await load();} else if(markBtn){const id=markBtn.dataset.id;const {error}=await client.from('mentor_comments').update({status:'addressed'}).eq('id',id);if(error){dashStatus.textContent=error.message;return;}dashStatus.textContent='Marked as addressed.';await load();}});
client.auth.onAuthStateChange(()=>load());load();
})();
