const observer = 'IntersectionObserver' in window ? new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) entry.target.classList.add('in-view');
  });
}, {threshold: .08}) : null;
document.querySelectorAll('.project-card,.timeline-item,.achievement,.community-card,.learning-column,.question-grid>div,.experience-card,.community-card,.blog-card').forEach(el => {
  el.classList.add('reveal'); if (observer) observer.observe(el); else el.classList.add('in-view');
});

const projectData = {
  'NeuroAccess': {
    kicker:'ACCESSIBILITY · WEB APP', intro:'A practical digital project exploring how technology can make support and information more accessible.',
    problem:'Accessibility is often discussed in abstract terms. I wanted to think about how a digital product could respond to concrete needs with a simple, usable interface.',
    idea:'A modern web experience bringing useful functionality together in one place, with an emphasis on clarity, usability and future scalability.',
    role:'Product thinking, interface work, frontend development and deployment. I also worked across the backend/frontend setup and environment configuration.',
    stack:['Next.js','React','Supabase','Render','Vercel'],
    learning:'Building NeuroAccess taught me to think beyond a screen: architecture, deployment, user flows and the small details that make a product feel coherent.',
    links:[['GitHub','#'],['Live demo','#']]
  },
  'Reflex': {
    kicker:'AI LITERACY · INFORMATION INTEGRITY', intro:'A project built around a simple habit: pause, question, verify.',
    problem:'AI-generated and manipulated media make it increasingly difficult to know what deserves trust. The challenge is not only detection — it is helping people develop better verification habits.',
    idea:'Reflex turns verification into a mental reflex, with a visual identity and product direction centered around stopping for a second before believing or sharing.',
    role:'Concept development, product thinking, project framing and visual direction.',
    stack:['AI literacy','Deepfakes','Information integrity','Product design'],
    learning:'The project pushed me to think about responsible AI from the user side: not only “can we detect it?” but “how can we help people reason about it?”',
    links:[['GitHub','#'],['Project page','#']]
  },
  'Language Detector': {
    kicker:'NLP · LOCAL LANGUAGES', intro:'An exploration of language detection across French, English, Hausa and Zarma.',
    problem:'Many AI language tools are optimized for high-resource languages. That creates a gap for multilingual communities whose everyday languages are less represented in datasets and products.',
    idea:'Build a language-detection experiment that recognizes several languages relevant to the Sahelian context.',
    role:'Data exploration, Python experimentation, NLP/model thinking and testing.',
    stack:['Python','NLP','Classification','Hausa','Zarma','French','English'],
    learning:'This work made me think more critically about datasets, representation and the difference between a model that works technically and one that is useful in context.',
    links:[['GitHub','#'],['Demo','#']]
  },
  'Mama HealthID': {
    kicker:'HEALTHTECH · DIGITAL TOOLS', intro:'A health-oriented concept exploring clearer access to useful health information.',
    problem:'Digital health solutions can become complicated quickly. The challenge is making information easier to access, understand and organize.',
    idea:'A user-centered digital concept designed around accessibility, information organization and practical support.',
    role:'Project ideation, product framing and technical exploration.',
    stack:['HealthTech','Product','AI','UX'],
    learning:'The project reinforced my interest in technology that supports people in moments where clarity and accessibility really matter.',
    links:[['GitHub','#'],['Demo','#']]
  },
  'Civix Niger': {
    kicker:'CIVIC TECH · NIGER', intro:'A civic technology concept inspired by participation, information and local realities.',
    problem:'Civic tools can feel distant from the communities they are designed for. I wanted to explore what more locally grounded civic technology could look like.',
    idea:'A digital concept connecting technology with civic participation and useful public information.',
    role:'Concept development, product thinking and technical exploration.',
    stack:['CivicTech','Product','Web','Social impact'],
    learning:'Civix Niger helped me connect my interest in technology with questions of governance, trust and participation.',
    links:[['GitHub','#'],['Demo','#']]
  },
  'Cooking 227': {
    kicker:'CULTURE · DIGITAL PRODUCT', intro:'A project rooted in everyday life, food and local culture.',
    problem:'Digital products often overlook the cultural context that makes information meaningful. Cooking 227 explored how a familiar subject can become a digital experience.',
    idea:'A product concept centered around recipes, discovery and local identity.',
    role:'Project ideation, content direction and technical exploration.',
    stack:['Product','Culture','Web','Content'],
    learning:'It reminded me that “useful” technology can also be personal, cultural and joyful.',
    links:[['GitHub','#'],['Demo','#']]
  },
  'Saheli': {
    kicker:'SAHEL · TECHNOLOGY', intro:'A concept centered on building digital experiences with the Sahel in mind.',
    problem:'Technology is often designed from assumptions that do not match local infrastructure, language or user habits.',
    idea:'Explore what it means to build products that begin from Sahelian realities instead of adapting them afterward.',
    role:'Research, concept development and product exploration.',
    stack:['Sahel','Product','Technology','Research'],
    learning:'The project sharpened one of my favorite questions: what changes when the context is the starting point?',
    links:[['GitHub','#'],['Project page','#']]
  },
  'Reading of the Sahel': {
    kicker:'EDTECH · CULTURE', intro:'An educational concept exploring reading, resources and access through a local lens.',
    problem:'Access to learning resources is not only a question of availability — it is also about language, relevance, discoverability and context.',
    idea:'A digital reading concept designed to think about learning through a Sahelian perspective.',
    role:'Concept development, research and product framing.',
    stack:['Education','Culture','Digital access','Product'],
    learning:'It made me more interested in how technology can widen access without flattening local identity.',
    links:[['GitHub','#'],['Demo','#']]
  },
  'AI + Agriculture': {
    kicker:'AGRITECH · AI · DRONES', intro:'Explorations around applying AI and drone technology to agricultural contexts.',
    problem:'Agriculture generates complex visual and operational information, while farmers and agricultural organizations need practical ways to turn that information into decisions.',
    idea:'Explore drone-assisted data collection and AI-based analysis as tools that could support agricultural monitoring and resource management.',
    role:'Problem exploration, AI ideation, prototyping and connection to real agricultural contexts through my experience at Protra Niger.',
    stack:['AI','Drones','Agriculture','Computer Vision','Prototyping'],
    learning:'This is where my technical interests and real-world environment meet most directly — building technology around problems I can actually see.',
    links:[['GitHub','#'],['Demo','#']]
  }
};

const projectModal = document.getElementById('projectModal');
function t(s){ return window.MarieI18n?.t ? window.MarieI18n.t(s) : s; }
function openProject(name){
  const d = projectData[name]; if(!d) return;
  document.getElementById('projectModalKicker').textContent=t(d.kicker);
  document.getElementById('projectModalTitle').textContent=t(name);
  document.getElementById('projectModalIntro').textContent=t(d.intro);
  document.getElementById('projectProblem').textContent=t(d.problem);
  document.getElementById('projectIdea').textContent=t(d.idea);
  document.getElementById('projectRole').textContent=t(d.role);
  document.getElementById('projectLearning').textContent=t(d.learning);
  document.getElementById('projectStack').innerHTML=d.stack.map(x=>`<span>${t(x)}</span>`).join('');
  document.getElementById('projectActions').innerHTML=d.links.map(([label,url])=>`<a class="btn btn-dark" href="${url}" target="_blank" rel="noreferrer">${t(label)} ↗︎</a>`).join('');
  projectModal.classList.add('show'); projectModal.setAttribute('aria-hidden','false'); document.body.classList.add('modal-open');
}

document.querySelectorAll('.project-card').forEach(card=>{
  const title=card.querySelector('h3')?.textContent.trim();
  card.addEventListener('click',e=>{ if(e.target.closest('a')) return; openProject(title); });
  card.addEventListener('keydown',e=>{ if(e.key==='Enter' || e.key===' '){e.preventDefault(); openProject(title);} });
  card.querySelector('.case-link')?.addEventListener('click',e=>{e.stopPropagation(); openProject(title);});
});

const blogs={
 'ai-africa':{kicker:'AI & IMPACT · 2026',title:'Why I keep coming back to AI for African contexts',byline:'A personal note by Marie · 6 min read',html:`<p>I like technology most when the problem comes first. Growing up in Niger has made that instinct hard to ignore: the best solution is not always the most sophisticated one. It is the one that actually fits the people, infrastructure, languages and habits around it.</p><p>That is why I keep coming back to questions around healthcare, agriculture, local languages, misinformation and access. They are not “African versions” of abstract AI problems. They are real problems in their own right, and they deserve ambitious technology.</p><h3>Context changes the design</h3><p>A product can be technically impressive and still be a poor fit. Connectivity, language, trust, digital literacy and workflow all matter. I want my AI education to help me understand both the model and the context around the model.</p><p>This is also why projects like my language detector, agriculture experiments and Reflex keep connecting in my mind. They look different, but they share a question: <em>how do we make technology useful here?</em></p><h3>Still figuring it out</h3><p>I don't think I have the answer yet. Part of the point of this journal is to document the process — the experiments that work, the ones that don't, and the ideas that change after meeting reality.</p>`},
 'building-public':{kicker:'BUILDING · 2026',title:"What building projects has taught me that class couldn't",byline:'A personal note by Marie · 4 min read',html:`<p>Courses teach you foundations. Projects force you to make decisions.</p><p>When I build something, there is always a moment where the neat plan disappears: a dependency breaks, the deployment behaves differently, the data is messy, or the feature that sounded brilliant suddenly makes no sense for the user.</p><h3>That mess is useful</h3><p>Working on projects like NeuroAccess has taught me to care about the full journey — idea, interface, backend, deployment, testing and communication. It made “building” feel much bigger than writing code.</p><p>I have also learned that a small working prototype teaches me more than a perfect plan sitting in a notebook. You can learn faster once there is something real to react to.</p><h3>My current rule</h3><p>Start small. Ship something. Listen. Improve. Repeat.</p>`},
 'soft-start':{kicker:'PERSONAL · 2026',title:'Learning to be ambitious without making everything urgent',byline:'A personal note by Marie · 3 min read',html:`<p>There is a particular kind of student pressure that comes from seeing opportunities everywhere. Scholarships, competitions, internships, courses, fellowships, projects — suddenly every open application feels like something you are supposed to become.</p><p>I am learning that ambition works better when it has direction.</p><h3>Not every opportunity has to be mine</h3><p>Some opportunities are amazing but not aligned with the person I am trying to become. Saying no — or simply letting an application pass — can be a form of focus.</p><h3>Progress needs softness too</h3><p>I want to keep aiming high without turning my life into one long deadline. There is room for curiosity, mistakes, rest and changing my mind.</p><p>Maybe “soft” and “ambitious” were never opposites.</p>`},
 'local-languages':{kicker:'LOCAL AI · 2026',title:'Why local languages belong in the AI conversation',byline:'A personal note by Marie · 5 min read',html:`<p>When we talk about inclusive AI, language is one of the first places I look.</p><p>In the Sahel, people navigate multiple languages every day. Yet many AI systems are still strongest in a much smaller set of high-resource languages. That gap affects search, translation, voice interfaces, education and access to information.</p><h3>Representation is not a feature</h3><p>Adding a language to a product is not just a checkbox. Data quality, spelling variation, cultural context, evaluation and community participation all matter.</p><p>My own language-detection experiments with Hausa and Zarma are small, but they changed the way I think about datasets. A model can only learn from what it is given — and what it is given reflects our priorities.</p><h3>What I want to explore next</h3><p>I want to understand more about NLP for underrepresented languages, responsible dataset creation and how local communities can be part of the process rather than just the audience.</p>`}
};
const blogModal=document.getElementById('blogModal');
function openBlog(id){const d=blogs[id]; if(!d)return; document.getElementById('blogModalKicker').textContent=d.kicker; document.getElementById('blogModalTitle').textContent=d.title; document.getElementById('blogModalByline').textContent=d.byline; document.getElementById('blogModalContent').innerHTML=d.html; blogModal.classList.add('show');blogModal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}
document.querySelectorAll('[data-blog]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();openBlog(el.dataset.blog);}));

document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(projectModal)));
document.querySelectorAll('[data-close-blog]').forEach(b=>b.addEventListener('click',()=>closeModal(blogModal)));
function closeModal(el){el?.classList.remove('show');el?.setAttribute('aria-hidden','true'); if(!document.querySelector('.overlay.show')) document.body.classList.remove('modal-open');}
document.querySelectorAll('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)closeModal(o);}));
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.overlay.show').forEach(closeModal);});

// Activity chapters — each experience opens like its own magazine page.
const activityData = {
  protra:{kicker:'PROFESSIONAL · AGRICULTURE · TECHNOLOGY',title:'Protra Niger',intro:'Hands-on experience inside a family agro-transformation company, where technology meets a real business and agricultural environment.',meta:['Ongoing','Niamey · Niger','Technology + Agriculture'],story:'Working with Protra Niger gave me a perspective that a classroom cannot fully reproduce: seeing how an organization actually works, where information gets lost, what needs to be communicated, and where digital tools can make everyday work easier.',role:'I contributed to communication and to the exploration and development of digital tools, including an application for agricultural resource management and AI-oriented prototypes.',did:'Communication support; digital tool development; agricultural resource-management ideas; AI experimentation inspired by real use cases; connecting technical learning to an operating business.',learning:'It taught me to start with the workflow and the people, not with the technology. A solution has to fit the way work is really done.',add:['Company / workplace photos','Screenshots of the agricultural resource-management tool','Prototype screenshots or diagrams','A short reflection from the company context','GitHub or demo link, when public']},
  tcc:{kicker:'LEADERSHIP · ADU · COMMUNITY',title:'Tech Communities Club — ADU',intro:'My journey from Event Planner to Co-lead in a student technology community.',meta:['Event Planner →︎ Co-lead','African Development University','Leadership'],story:'TCC became one of the spaces where I learned that technology communities are built by people, not just events. I moved from helping organize activities to taking a stronger role in shaping how the community works.',role:'Event planning first, then co-leading: helping coordinate activities, support student initiatives, communicate with members and contribute to the wider ADU tech ecosystem.',did:'Event organization; coordination; community communication; teamwork; supporting student technology activities; taking responsibility for execution.',learning:'Leadership became much more concrete for me when I had to turn ideas into something other people could actually participate in.',add:['Event posters / flyers','Photos from TCC events','Certificates or appointment proof','Screenshots of announcements','Numbers: events, workshops, participants — if available']},
  ylp:{kicker:'LEADERSHIP · YOUTH DEVELOPMENT',title:'Youth Leadership Program — Cohort 5',intro:'Serving as President of Cohort 5 and learning what it means to represent a group of peers.',meta:['President · Cohort 5','Youth Leadership Program','Leadership + Representation'],story:'Being President of my cohort gave me a role that was less about having the loudest voice and more about making sure people felt represented, informed and connected.',role:'Cohort coordination, communication, representation and helping maintain a sense of community among peers.',did:'Communicating information; coordinating with peers; representing the cohort; encouraging participation; helping create a collaborative cohort culture.',learning:'I am learning that leadership is a balance between direction and listening. Representation only works when you understand the people you are representing.',add:['Cohort group photos','Appointment / election proof','Screenshots of cohort communication','Photos from cohort activities','Any speech, reflection or leadership deliverable']},
  hundred:{kicker:'GLOBAL · EDUCATION · YOUTH VOICE',title:'HundrED × IB — Youth Ambassador',intro:'An international youth role connecting my IB background, education and interest in innovation.',meta:['Youth Ambassador','HundrED × International Baccalaureate','Global engagement'],story:'This opportunity connected me with a wider education and youth-innovation community. It also gave me a space to think beyond my own studies and consider how young people can contribute to conversations about the future of education.',role:'Participating as a youth ambassador, bringing a student perspective and engaging with an international education community.',did:'Youth engagement; sharing perspectives; learning from other young people and education-focused initiatives; representing my background and context.',learning:'Young people do not have to wait until they are “experts” to contribute. Perspective and lived experience are also valuable forms of knowledge.',add:['Acceptance / ambassador proof','Official program graphics','Photos from sessions','Your ambassador badge or profile','Links to any published contribution']},
  worldbank:{kicker:'GLOBAL · YOUTH · POLICY',title:'World Bank Youth Summit 2026',intro:'Participating as a youth delegate in a global conversation around development and the future.',meta:['Delegate · 2026','World Bank Youth Summit','Global exposure'],story:'Being part of the Youth Summit exposed me to conversations larger than a university classroom — development, policy, technology, opportunity and the role of young people in shaping what comes next.',role:'Participating as a youth delegate, listening, learning and contributing a young person’s perspective.',did:'Engaging with summit sessions; reflecting on development questions; connecting technology with broader social and economic conversations.',learning:'Technology does not exist separately from policy, economics or society. The bigger the problem, the more interdisciplinary the conversation becomes.',add:['Delegate confirmation','Event screenshots','Photos / virtual event captures','Notes from sessions','Any certificate of participation']},
  aoai:{kicker:'COMPETITION · ARTIFICIAL INTELLIGENCE',title:'AOAI — Bronze Medal',intro:'Competing in AI and representing Niger, with a Bronze Medal result.',meta:[' Bronze medal','Representing Niger','AI competition'],story:'This competition gave me the experience of testing my AI knowledge under pressure and seeing how much disciplined preparation matters when the questions get difficult.',role:'Competitor representing Niger.',did:'Prepared for AI problem-solving challenges; applied technical knowledge under competition conditions; learned from mistakes and comparison with other participants.',learning:'Competition taught me that knowing concepts is only part of the job. You also need speed, strategy, resilience and the ability to stay calm when you do not immediately know the answer.',add:['Medal photo','Official result / certificate','Competition platform screenshots','Preparation notes','Any ranking or score evidence']},
  ioai:{kicker:'COMPETITION · ARTIFICIAL INTELLIGENCE',title:'International Olympiad in Artificial Intelligence',intro:'Selected for IOAI, followed by an eligibility issue related to the competition rules.',meta:['Selected','IOAI','Eligibility lesson'],story:'Being selected was exciting because it validated the work I had been putting into AI. The later eligibility issue was disappointing, but it also became a reminder that opportunities have rules and that setbacks do not erase the achievement that came before them.',role:'Selected participant / candidate.',did:'Prepared for the selection process; engaged with the opportunity; navigated the eligibility issue and continued building my AI path afterward.',learning:'A setback can change the route without changing the destination. I kept the experience as evidence that I belong in challenging AI spaces.',add:['Selection email / proof','Official program logo','Eligibility communication, only if comfortable sharing','Preparation material','A short personal reflection']},
  hackathon:{kicker:'COMPETITION · BUILDING',title:'Hackathon — 4th Place',intro:'A fast-paced build where an idea had to become something presentable under time pressure.',meta:['4th place','Hackathon','Team + execution'],story:'Hackathons compress the whole product cycle: identify a problem, define a solution, build, test and pitch — often with far less time than you would like.',role:'Contributed to project development, problem-solving, technical work and presentation.',did:'Worked with teammates; translated an idea into a prototype; iterated quickly; prepared a final presentation and learned from competing teams.',learning:'Speed is not the same as rushing. The best hackathon work comes from making quick decisions while still keeping the problem at the center.',add:['Team photo','Project screenshots','Pitch deck','Final ranking / certificate','GitHub or demo link']},
  kaggle:{kicker:'DATA · COMPETITION',title:'Kaggle — Breast Cancer Classification',intro:'A machine-learning competition experience centered on classification.',meta:['Kaggle','Classification','Machine Learning'],story:'This was a practical opportunity to work with a real dataset and think about the difference between learning a model and building a reliable classification workflow.',role:'Participant working on the classification task.',did:'Data preparation; model experimentation; evaluation; iteration; reading performance critically rather than treating a score as the whole story.',learning:'Competition datasets are messy enough to teach you quickly that data quality, validation and assumptions matter just as much as model choice.',add:['Kaggle profile / competition link','Notebook screenshot','Model result','Confusion matrix / evaluation graphic','Lessons learned']},
  healtrack:{kicker:'HACKATHON · HEALTHTECH · AI',title:'HealTrack',intro:'A health-tech hackathon concept combining voice, automation and AI-assisted follow-up.',meta:['Hackathon','HealthTech','AI + Voice + Automation'],story:'I explored how a patient follow-up workflow could become more proactive by combining voice calls, transcription, notifications and automation.',role:'Contributed ideas around the user workflow, automation and AI architecture.',did:'Designed ideas involving Deepgram transcription, Vonage calls/notifications, Gmail automation for renewals, a daily check-in flow and AI-assisted triage connected to a dashboard.',learning:'The strongest part of the idea was not one API. It was the workflow — how several small technologies could work together to support a real human need.',add:['Architecture diagram','User flow','Prototype screenshots','API logos / technical stack','Team / hackathon proof']},
  sos:{kicker:'SERVICE · COMMUNITY',title:'SOS Children’s Village',intro:'A volunteering day centered on community, presence and giving time.',meta:['Volunteering','Community service','Local engagement'],story:'This experience reminded me that impact is not always measured in lines of code or certificates. Sometimes it is simply showing up, participating and giving attention to a community.',role:'Volunteer participant.',did:'Contributed time and energy during a community-focused volunteering day and participated in activities with others.',learning:'Service makes me think about impact in a broader way: people need presence, dignity and connection as much as they need technology.',add:['Photos from the volunteering day','Volunteer confirmation','Activity poster','A short reflection','Any group certificate']},
  schoolfair:{kicker:'COMMUNITY · SCHOOL',title:'School Fair',intro:'A school/community event where collaboration and participation mattered as much as the activity itself.',meta:['Community activity','School event','Collaboration'],story:'School events taught me another kind of teamwork: organizing around a shared experience, communicating clearly and making sure people can participate.',role:'Participant / contributor in the school fair activity.',did:'Supported the event experience and participated in the collaborative work around the fair.',learning:'Community-building often happens through small, practical contributions that make an event feel welcoming and organized.',add:['Event photographs','Poster or programme','Role description','Participation evidence, if available','Personal reflection']},
  speaking:{kicker:'PERSONAL DEVELOPMENT · COMMUNICATION',title:'Public Speaking',intro:'A continuous learning activity: becoming more comfortable expressing ideas clearly and confidently.',meta:['Communication','Personal growth','Presentation'],story:'Technical skills matter, but an idea only travels when you can explain it. Public speaking has become part of how I work on the other side of my technical profile.',role:'Learner and speaker in academic, community and professional contexts.',did:'Practicing presentations; explaining technical ideas; participating in discussions; working on confidence, structure and delivery.',learning:'I am learning that confidence is not about never being nervous. It is about knowing what you want to say and saying it anyway.',add:['Presentation slides and examples','Relevant event documentation','Speaking-related certificates, when available','Video or presentation links','A short reflection on progress']},
  research:{kicker:'RESEARCH · SOCIAL QUESTIONS',title:'Research Explorations',intro:'A collection of questions I have explored around AI, society and problems I care about.',meta:['Research','AI + society','Exploration'],story:'My research interests often begin with a simple question: where could technology actually change something meaningful? I have explored ideas around AI for anti-corruption work and social issues such as begging in Niamey.',role:'Independent student researcher / explorer.',did:'Framing questions; comparing possible uses of AI; thinking about ethical and practical constraints; connecting technical possibilities to local problems.',learning:'Good research starts before the model. It starts with asking whether the problem is well-defined, whether the proposed intervention is useful and who it affects.',add:['Research notes','Problem statements','Concept maps','References','Questions for future work']}
};

const activityModal=document.getElementById('activityModal');
function openActivity(id){const d=activityData[id];if(!d)return;document.getElementById('activityModalKicker').textContent=d.kicker;document.getElementById('activityModalTitle').textContent=d.title;document.getElementById('activityModalIntro').textContent=d.intro;document.getElementById('activityModalMeta').innerHTML=d.meta.map(x=>`<span>${x}</span>`).join('');document.getElementById('activityStory').textContent=d.story;document.getElementById('activityRole').textContent=d.role;document.getElementById('activityDid').textContent=d.did;document.getElementById('activityLearning').textContent=d.learning;document.getElementById('activityAdditions').innerHTML=d.add.map(x=>`<span> ${x}</span>`).join('');activityModal.classList.add('show');activityModal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}

document.querySelectorAll('[data-activity]').forEach(el=>{el.addEventListener('click',e=>{if(e.target.closest('a,button'))return;if(el.dataset.href){window.location.href=el.dataset.href;return;}openActivity(el.dataset.activity)});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(el.dataset.href){window.location.href=el.dataset.href;}else{openActivity(el.dataset.activity)}}})});
document.querySelectorAll('[data-close-activity]').forEach(b=>b.addEventListener('click',()=>closeModal(activityModal)));

document.querySelectorAll('.filter-chip').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-chip').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.activityFilter;document.querySelectorAll('.activity-tile').forEach(card=>card.style.display=f==='all'||card.dataset.category===f?'flex':'none')}));

const takes={
 'ai-africa':{cat:'AI & TECH',title:'What should AI look like in Africa?',html:`<p>I don't think there is one “African AI.” Africa is too diverse for that. But I do think AI built for African contexts should start from local realities instead of treating them as an afterthought.</p><h3>Context should come first</h3><p>Connectivity, cost, language, infrastructure, trust and everyday habits affect whether a product is useful. A technically impressive system that ignores those realities can still fail.</p><p>For me, the interesting question is not simply <em>“Can we build it?”</em> but <em>“Does this make sense here, for these people, in this context?”</em></p>`},
 'local-ai':{cat:'AI & TECH',title:'Why do local languages matter so much?',html:`<p>Language is access. When an AI system understands only the languages with the most data, the people who use other languages are not just missing a feature — they can be missing an entire layer of digital participation.</p><p>Working on Hausa and Zarma made this personal for me. It made datasets feel less abstract and made me think about who gets represented in the systems we build.</p><h3>Inclusion is technical</h3><p>Good intentions are not enough. We need better data, evaluation, tooling and community participation for underrepresented languages.</p>`},
 'impact':{cat:'AFRICA & IMPACT',title:'Can technology really create social impact?',html:`<p>Yes — but not automatically. Building an app does not equal solving a problem.</p><p>Impact starts with understanding the problem, the people involved and what success actually looks like. Technology is one possible tool inside that larger process.</p><h3>What I try to remember</h3><p>Start with people. Test with reality. Measure something meaningful. Be willing to change the product when the problem tells you that you are wrong.</p>`},
 'leadership':{cat:'LEADERSHIP',title:'What does being a good student leader mean to me?',html:`<p>For me, leadership is not mainly about titles. Being President of my Youth Leadership cohort and serving as a Co-lead in TCC are teaching me that leadership is mostly responsibility.</p><p>It means communicating clearly, listening before deciding, following through and making other people feel that they belong in the room.</p><p>I am still learning, but I want my leadership to leave a community stronger than I found it.</p>`},
 'ambition':{cat:'STUDENT LIFE',title:'How do I think about ambition?',html:`<p>I am ambitious. I also want that ambition to be sustainable.</p><p>There are always more applications, competitions, courses and projects. I am learning that not every opportunity deserves the same amount of attention.</p><h3>My rule</h3><p>I would rather build a few meaningful things and understand why I am doing them than collect opportunities just because they are impressive.</p>`},
 'failure':{cat:'STUDENT LIFE',title:'What have setbacks taught me?',html:`<p>Setbacks have made me less attached to one specific route.</p><p>The IOAI eligibility issue, difficult technical problems and projects that did not immediately work all taught me a version of the same lesson: progress is not always linear.</p><p>I try to keep the evidence of what went well, learn from what did not, and keep moving without pretending disappointment did not happen.</p>`},
 'future':{cat:'AFRICA & IMPACT',title:'What do I want to contribute to the Nigerien tech ecosystem?',html:`<p>I want to contribute as a builder and as someone who understands the local context.</p><p>Niger should not only be a consumer of technologies designed elsewhere. I would love to see more people creating products, research and companies from here — with the ambition to serve both local needs and wider markets.</p><p>My own path is still evolving, but I want African context to remain part of my technical identity, not a footnote in it.</p>`},
 'responsible':{cat:'AI & TECH',title:'What does responsible AI mean to me?',html:`<p>Responsible AI is bigger than accuracy.</p><p>For me it includes usefulness, safety, accessibility, transparency, privacy, context and the ability to question whether a model should be used at all.</p><p>Projects like Reflex have made me think especially about the human side of AI: trust, misinformation and the habits people develop around technology.</p>`}
};
const takeModal=document.getElementById('takeModal');
function openTake(id){const d=takes[id];if(!d)return;document.getElementById('takeModalKicker').textContent=d.cat;document.getElementById('takeModalTitle').textContent=d.title;document.getElementById('takeModalContent').innerHTML=d.html;takeModal.classList.add('show');takeModal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}
document.querySelectorAll('[data-take]').forEach(el=>{el.addEventListener('click',()=>openTake(el.dataset.take));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openTake(el.dataset.take)}})});
document.querySelectorAll('.take-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.take-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.takeFilter;document.querySelectorAll('.take-card').forEach(card=>card.style.display=f==='all'||card.dataset.takeCategory===f?'block':'none')}));
document.querySelectorAll('[data-close-take]').forEach(b=>b.addEventListener('click',()=>closeModal(takeModal)));
